/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP"
 * 	found in "f1ap.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_F1AP_PDU_H_
#define	_F1AP_PDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include "InitiatingMessage.h"
#include "SuccessfulOutcome.h"
#include "UnsuccessfulOutcome.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum F1AP_PDU_PR {
	F1AP_PDU_PR_NOTHING,	/* No components present */
	F1AP_PDU_PR_initiatingMessage,
	F1AP_PDU_PR_successfulOutcome,
	F1AP_PDU_PR_unsuccessfulOutcome
} F1AP_PDU_PR;

/* F1AP-PDU */
typedef struct F1AP_PDU {
	F1AP_PDU_PR present;
	union F1AP_PDU_u {
		InitiatingMessage_t	 initiatingMessage;
		SuccessfulOutcome_t	 successfulOutcome;
		UnsuccessfulOutcome_t	 unsuccessfulOutcome;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} F1AP_PDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_F1AP_PDU;

#ifdef __cplusplus
}
#endif

#endif	/* _F1AP_PDU_H_ */
#include <asn_internal.h>
