/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP"
 * 	found in "f1ap.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_F1HandoverRequest_H_
#define	_F1HandoverRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <BIT_STRING.h>
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum F1HandoverRequest__handoverType {
	F1HandoverRequest__handoverType_intra_freq	= 0,
	F1HandoverRequest__handoverType_inter_freq	= 1,
	F1HandoverRequest__handoverType_inter_rat	= 2
} e_F1HandoverRequest__handoverType;

/* F1HandoverRequest */
typedef struct F1HandoverRequest {
	long	 transactionID;
	BIT_STRING_t	 sourceCellID;
	BIT_STRING_t	 targetCellID;
	long	 handoverType;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} F1HandoverRequest_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_handoverType_5;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_F1HandoverRequest;

#ifdef __cplusplus
}
#endif

#endif	/* _F1HandoverRequest_H_ */
#include <asn_internal.h>
