/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP"
 * 	found in "f1ap.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_F1HandoverResponse_H_
#define	_F1HandoverResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <BIT_STRING.h>
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum F1HandoverResponse__status {
	F1HandoverResponse__status_success	= 0,
	F1HandoverResponse__status_partial	= 1,
	F1HandoverResponse__status_failure	= 2
} e_F1HandoverResponse__status;

/* F1HandoverResponse */
typedef struct F1HandoverResponse {
	long	 transactionID;
	BIT_STRING_t	 targetCellID;
	long	 status;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} F1HandoverResponse_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_status_4;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_F1HandoverResponse;

#ifdef __cplusplus
}
#endif

#endif	/* _F1HandoverResponse_H_ */
#include <asn_internal.h>
