/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP"
 * 	found in "f1ap.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_F1ReleaseResponse_H_
#define	_F1ReleaseResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum F1ReleaseResponse__result {
	F1ReleaseResponse__result_success	= 0,
	F1ReleaseResponse__result_failure	= 1
} e_F1ReleaseResponse__result;

/* F1ReleaseResponse */
typedef struct F1ReleaseResponse {
	long	 transactionID;
	long	 result;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} F1ReleaseResponse_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_result_3;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_F1ReleaseResponse;

#ifdef __cplusplus
}
#endif

#endif	/* _F1ReleaseResponse_H_ */
#include <asn_internal.h>
