/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP"
 * 	found in "f1ap.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_F1SetupRequest_H_
#define	_F1SetupRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <BIT_STRING.h>
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolIE_Container;

/* F1SetupRequest */
typedef struct F1SetupRequest {
	long	 transactionID;
	BIT_STRING_t	 gNB_ID;
	OCTET_STRING_t	*gNB_Name	/* OPTIONAL */;
	struct ProtocolIE_Container	*cells_to_be_activated	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} F1SetupRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_F1SetupRequest;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ProtocolIE-Container.h"

#endif	/* _F1SetupRequest_H_ */
#include <asn_internal.h>
