/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP"
 * 	found in "f1ap.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_F1SetupFailure_H_
#define	_F1SetupFailure_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum F1SetupFailure__cause {
	F1SetupFailure__cause_unspecified	= 0,
	F1SetupFailure__cause_overload	= 1,
	F1SetupFailure__cause_invalidID	= 2
} e_F1SetupFailure__cause;
typedef enum F1SetupFailure__timeToWait {
	F1SetupFailure__timeToWait_vshort	= 0,
	F1SetupFailure__timeToWait_short	= 1,
	F1SetupFailure__timeToWait_medium	= 2,
	F1SetupFailure__timeToWait_long	= 3
} e_F1SetupFailure__timeToWait;

/* F1SetupFailure */
typedef struct F1SetupFailure {
	long	 transactionID;
	long	 cause;
	long	*timeToWait	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} F1SetupFailure_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_cause_3;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_timeToWait_7;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_F1SetupFailure;

#ifdef __cplusplus
}
#endif

#endif	/* _F1SetupFailure_H_ */
#include <asn_internal.h>
