/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP"
 * 	found in "f1ap.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_InitiatingMessage_H_
#define	_InitiatingMessage_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include "F1SetupRequest.h"
#include "F1ReleaseRequest.h"
#include "F1HandoverRequest.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum InitiatingMessage__criticality {
	InitiatingMessage__criticality_reject	= 0,
	InitiatingMessage__criticality_ignore	= 1,
	InitiatingMessage__criticality_notify	= 2
} e_InitiatingMessage__criticality;
typedef enum InitiatingMessage__value_PR {
	InitiatingMessage__value_PR_NOTHING,	/* No components present */
	InitiatingMessage__value_PR_f1SetupRequest,
	InitiatingMessage__value_PR_f1ReleaseRequest,
	InitiatingMessage__value_PR_f1HandoverRequest
} InitiatingMessage__value_PR;

/* InitiatingMessage */
typedef struct InitiatingMessage {
	long	 procedureCode;
	long	 criticality;
	struct InitiatingMessage__value {
		InitiatingMessage__value_PR present;
		union InitiatingMessage__value_u {
			F1SetupRequest_t	 f1SetupRequest;
			F1ReleaseRequest_t	 f1ReleaseRequest;
			F1HandoverRequest_t	 f1HandoverRequest;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} InitiatingMessage_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_criticality_3;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_InitiatingMessage;

#ifdef __cplusplus
}
#endif

#endif	/* _InitiatingMessage_H_ */
#include <asn_internal.h>
