/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP"
 * 	found in "f1ap.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_ProtocolIE_Field_H_
#define	_ProtocolIE_Field_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include <BIT_STRING.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ProtocolIE_Field__criticality {
	ProtocolIE_Field__criticality_reject	= 0,
	ProtocolIE_Field__criticality_ignore	= 1,
	ProtocolIE_Field__criticality_notify	= 2
} e_ProtocolIE_Field__criticality;
typedef enum ProtocolIE_Field__value_PR {
	ProtocolIE_Field__value_PR_NOTHING,	/* No components present */
	ProtocolIE_Field__value_PR_gNB_ID,
	ProtocolIE_Field__value_PR_cellID,
	ProtocolIE_Field__value_PR_transactionID,
	/* Extensions may appear below */
	
} ProtocolIE_Field__value_PR;

/* ProtocolIE-Field */
typedef struct ProtocolIE_Field {
	long	 id;
	long	 criticality;
	struct ProtocolIE_Field__value {
		ProtocolIE_Field__value_PR present;
		union ProtocolIE_Field__value_u {
			BIT_STRING_t	 gNB_ID;
			BIT_STRING_t	 cellID;
			long	 transactionID;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Field_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_criticality_3;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Field;

#ifdef __cplusplus
}
#endif

#endif	/* _ProtocolIE_Field_H_ */
#include <asn_internal.h>
