/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP"
 * 	found in "f1ap.asn"
 * 	`asn1c -gen-PER -fcompound-names`
 */

#ifndef	_SuccessfulOutcome_H_
#define	_SuccessfulOutcome_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include "F1SetupResponse.h"
#include "F1ReleaseResponse.h"
#include "F1HandoverResponse.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SuccessfulOutcome__criticality {
	SuccessfulOutcome__criticality_reject	= 0,
	SuccessfulOutcome__criticality_ignore	= 1,
	SuccessfulOutcome__criticality_notify	= 2
} e_SuccessfulOutcome__criticality;
typedef enum SuccessfulOutcome__value_PR {
	SuccessfulOutcome__value_PR_NOTHING,	/* No components present */
	SuccessfulOutcome__value_PR_f1SetupResponse,
	SuccessfulOutcome__value_PR_f1ReleaseResponse,
	SuccessfulOutcome__value_PR_f1HandoverResponse
} SuccessfulOutcome__value_PR;

/* SuccessfulOutcome */
typedef struct SuccessfulOutcome {
	long	 procedureCode;
	long	 criticality;
	struct SuccessfulOutcome__value {
		SuccessfulOutcome__value_PR present;
		union SuccessfulOutcome__value_u {
			F1SetupResponse_t	 f1SetupResponse;
			F1ReleaseResponse_t	 f1ReleaseResponse;
			F1HandoverResponse_t	 f1HandoverResponse;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SuccessfulOutcome_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_criticality_3;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_SuccessfulOutcome;

#ifdef __cplusplus
}
#endif

#endif	/* _SuccessfulOutcome_H_ */
#include <asn_internal.h>
